name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make

    - name: Build
      shell: msys2 {0}
      run: |
        mingw32-make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChineseStrokeIME-Build
        path: ChineseStrokeIME.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ChineseStrokeIME.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
